import { Brygada_1918, Rubik } from "next/font/google";
import "./globals.css";
import Header from "./Component/Header";
import { Footer } from "./Component/Footer";


const brygada = Brygada_1918({
  subsets: ["latin"],
  weight: ["400", "700"], 
  variable: "--font-brygada",
});

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-rubik",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${brygada.variable} ${rubik.variable} antialiased max-w-[1280px]`}
      >
        <Header></Header>
        {children}
      <Footer></Footer>
      </body>
    </html>
  );
}
